---
# This playbook deploys Whydah to AWS AMI's

- name: Set up Whydah UserIdentityBackend
  hosts: Whydah_UserIdentityBackend
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    uib
  vars:
    username: UserIdentityBackend
    group_id: net/whydah/identity
    app_name: UserIdentityBackend
    version: 2.0-rc-2
    env_mode: PROD
    env_vars: -DIAM_MODE=PROD
    service_config_template: useridentitybackend.properties
    service_config: useridentitybackend.PROD.properties
    verify_service_url: http://localhost:9995/uib/authenticate/application/
  vars_files:
    - vars/uib

- name: Create STS hazelcast file
  hosts: Whydah_SecurityTokenService
  sudo: true
  roles:
    - configuration
  tags:
    sts
  vars:
    username: SecurityTokenService
    service_config_template: hazelcast.xml
    service_config: hazelcast.xml

- name: Set up Whydah SecurityTokenService
  hosts: Whydah_SecurityTokenService
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    sts
  vars:
    username: SecurityTokenService
    group_id: net/whydah/token
    app_name: SecurityTokenService
    version: 2.0-rc-2
    env_vars: -DIAM_MODE=PROD -Dhazelcast.config=hazelcast.xml
    service_config_template: securitytokenservice.properties
    service_config: securitytokenservice.PROD.properties
#    verify_service_url: http://localhost:9998/tokenservice/
  vars_files:
    - vars/securityTokenService

- name: Set up Whydah SSOLoginWebApp
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    sso
  vars:
    username: SSOLoginWebApp
    group_id: net/whydah/sso
    app_name: SSOLoginWebApp
    version: 2.0-rc-2
    env_vars: -DIAM_MODE=PROD
    service_config_template: ssologinservice.properties
    service_config: ssologinservice.PROD.properties
    verify_service_url: http://localhost:9997/sso/login
  vars_files:
    - vars/ssoLogin

- name: Set up Whydah UserAdminWebApp
  hosts: Whydah_UserAdminWebApp
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    admin
  vars:
    username: UserAdminWebApp
    group_id: net/whydah/identity
    app_name: UserAdminWebApp
    version: 2.0-rc-2
    env_vars: -DIAM_MODE=PROD
    service_config_template: useradminwebapp.properties
    service_config: useradminwebapp.PROD.properties
    verify_service_url: http://localhost:9996/useradmin
  vars_files:
    - vars/userAdministration

- name: Set up Whydah TestWebApp
  hosts: Whydah_TestWebApp
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    testapp
  vars:
    username: TestWebApp
    group_id: net/whydah/sso/web
    app_name: TestWebApp
    version: 2.0-rc-2
    env_vars: -DIAM_MODE=TEST
    service_port: 9990
    service_config_template: testwebapp.properties
    service_config: testwebapp.TEST.properties
    verify_service_url: http://localhost:9990/test/hello

- name: Set up Apache config
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - apache
  tags:
    apache