---
# This playbook deploys Whydah to AWS AMI's

- name: Set up LDAP for Whydah
  hosts: javaBin_LDAP
  sudo: true
  remote_user: ubuntu
  roles:
    - openldap
    - whydah_useradmin
  tags:
    ldap
    #verify_service_url: http://localhost:9995/uib/authenticate/application/
 # vars_files:
 #   - vars/uib
