---
# This playbook deploys Whydah to AWS AMI's

- name: Set up LDAP for Whydah
  hosts: javaBin_LDAP
  sudo: true
  roles:
    - standard
    - openldap
  tags:
    ldap
  vars:
    username: openldap
    app_name: openldap
    #verify_service_url: http://localhost:9995/uib/authenticate/application/
 # vars_files:
 #   - vars/uib