---
- name: Upgrade all packages
  yum: name=* state=latest

- name: Install standard linux utilities
  yum: name={{item}} state=present
  with_items:
  - telnet
  - lynx
  - wget
  - vim
  - java-1.8.0-openjdk

- name: Set server identifyer in bash
  lineinfile: dest=~/.bash_profile regexp="^export PS1=" line='export PS1="[\u@\h/{{deployment_identifyer}} \w]$"'
  sudo: false